### ISSUE TITLE
蝙蝠生成问题

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/InfernalMobs#15]
![image](https://user-images.githubusercontent.com/24622099/48548830-f1c48b00-e908-11e8-821a-1b4273c51b2c.png)

**Comment by RecursiveG** [comment]
请将`BAT`从配置文件中的`enabledMounts`中移除。
mounted技能不支持使用蝙蝠作为坐骑。
请使用flying技能作为替代。
