### ISSUE TITLE
build 5.6 bugs on mcmmo build v1.6.0-SNAPSHOT on 1.13.2 paper build 474

### ISSUE THREAD

**Issue by comonier** [NyaaCat/InfernalMobs#16]
https://codeshare.io/5NJ4M8
https://codeshare.io/2Bv4Lb
https://codeshare.io/5z4Wp4
https://codeshare.io/2Kn4pY
 
if i dont have infernal mobs, mcmmo works with no erros
if i have infernal mobs, all commands and stuffs on mcmmo have a lot of erros.

i take some days to found the mcmmo problem > is the inernal mobs 5.6
https://github.com/mcMMO-Dev/mcMMO/issues/3632

**Comment by comonier** [comment]
https://github.com/NyaaCat can you talk with 
https://github.com/mcMMO-Dev to try solve the problem ?

**Comment by FabioZumbi12** [comment]
Voca ta usando a versão do Eliminator, pra suporte a versão dele vc deve abrir um ticket aqui: https://bitbucket.org/Eliminator/infernalmobs/src/master/

As versões do Nyaa são 5.1
