### ISSUE TITLE
inf v2.0

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/InfernalMobs#22]
- [x] 击杀信息只广播到当前世界，再应用玩家的广播接收选项。
- [x] 当执行命令的玩家不是 op 时，不显示任何命令反馈。
- [x] `/im getloot` 如果玩家背包没有足够空间，物品将落在玩家脚下。
- [x] `findOpenArea` 重写
- [x] 反伤技能修改为按百分比反伤，有一个最大值

**Comment by ReinWD** [comment]
findOpenArea 相关方法暂时禁用，计划使用chunk操作重写
