### ISSUE TITLE
lifesteal uses real damage to steal life

### ISSUE THREAD

**Issue by ReinWD** [NyaaCat/InfernalMobs#8]
@ability/AbilityLifeSteal
ev.getDamage ()  returns real damage, which is not considered armors and potions.
That means that every time it is triggered, the Mob will get tons of life. It makes them really hard to be killed by low damage high frequency weapons.

**Comment by ReinWD** [comment]
besides, it's better to set a random chance to determine whether it will be activated.

**Comment by ReinWD** [comment]
According to Kanna_leeder's test, AbilityLifeSteal and AbilityVengeance made a damage-heal pair, resulting in heal after taken damage. If you use some low damage weapon, this pair makes it impossible to kill this Mob.
Maybe we should test whether damage is dealt by vengeance and cancel this bug-like healing event.

**Comment by RecursiveG** [comment]
fixed
https://github.com/NyaaCat/InfernalMobs/commit/2da97fe0c78cf2a08414363002b968e3ac1406cf
https://github.com/NyaaCat/InfernalMobs/commit/6fe2fce2365ff47069aec8674b23cdd11cb62ff0
